const Joi = require("joi");

const triageSchema = Joi.object({
  radialPulse: Joi.boolean(),
  noisyBreathing: Joi.boolean(),
  activeSeizures: Joi.boolean(),
  eyeMovement: Joi.string().allow("", null),
  verbalResponse: Joi.string().allow("", null),
  motorResponse: Joi.string().allow("", null),
  painScale: Joi.string().allow(""),
  cSpineInjury: Joi.boolean(),
  traumaType: Joi.string().allow("", null),
  fracture: Joi.boolean(),
  fractureRegion: Joi.string().allow("", null),
  amputation: Joi.boolean(),
  neckSwelling: Joi.boolean(),
  minorHeadInjury: Joi.boolean(),
  abrasion: Joi.boolean(),
  suspectedAbuse: Joi.boolean(),
  pregnancy: Joi.boolean(),
  trimester: Joi.string().allow("", null),
  breathlessness: Joi.boolean(),
  internalBleeding: Joi.boolean(),
  internalBleedingCause: Joi.string().allow("", null),
  poisoning: Joi.boolean(),
  poisoningCause: Joi.string().allow("", null),
  burn: Joi.boolean(),
  burnPercentage: Joi.string().allow("", null),
  hanging: Joi.boolean(),
  drowning: Joi.boolean(),
  electrocution: Joi.boolean(),
  heatStroke: Joi.boolean(),
  fever: Joi.boolean(),
  feverSymptoms: Joi.string().allow("", null),
  drugOverdose: Joi.boolean(),
  stoolPass: Joi.boolean(),
  urinePass: Joi.boolean(),
  swellingWound: Joi.boolean(),
  dizziness: Joi.boolean(),
  headache: Joi.boolean(),
  coughCold: Joi.boolean(),
  skinRash: Joi.boolean(),
  medicoLegal: Joi.boolean(),
  zone: Joi.string(),
  ward: Joi.string().allow("", null),
  lastKnownSequence: Joi.string().allow("", null),
  criticalCondition: Joi.string().allow("", null),
  timelineID: Joi.number().integer().allow("", null),
  hospitalID: Joi.number().integer().required(),
  addedOn: Joi.date()
    .timestamp()
    .default(() => new Date()),
  userID: Joi.number().integer().required()
});

const triageFormSchema = Joi.object({
  zone: Joi.string().max(255).required(),
  ward: Joi.string().max(255).required(),
  patientTimelineID: Joi.number().integer().required(),
  hospitalID: Joi.number().integer().required(),
  userID: Joi.number().integer().required(),
  hospitalID: Joi.number().integer().required(),
  addedOn: Joi.date()
    .timestamp()
    .default(() => new Date())
    .optional(),
  lastKnownSequence: Joi.string().optional(),
  criticalCondition: Joi.string().optional(),
  oxygen: Joi.number().integer().optional(),
  pulse: Joi.number().integer().optional(),
  temperature: Joi.number().optional(),
  bpH: Joi.number().integer().optional(),
  bpL: Joi.number().integer().optional(),
  respiratoryRate: Joi.number().integer().optional(),
  time: Joi.string().optional(),
  radialPulse: Joi.boolean().optional(),
  noisyBreathing: Joi.boolean().optional(),
  activeSeizures: Joi.boolean().optional(),
  cSpineInjury: Joi.boolean().optional(),
  angioedema: Joi.boolean().optional(),
  stridor: Joi.boolean().optional(),
  activeBleeding: Joi.boolean().optional(),
  incompleteSentences: Joi.boolean().optional(),
  capillaryRefill: Joi.string().optional(),
  alteredSensorium: Joi.boolean().optional(),
  activeBleedingType: Joi.string().optional().allow(""),
  eyeMovement: Joi.string().optional(),
  verbalResponse: Joi.string().optional(),
  motorResponse: Joi.string().optional(),
  painScale: Joi.string().optional(),
  traumaType: Joi.string().optional(),
  fallHeight: Joi.string().optional(),
  fracture: Joi.boolean().optional(),
  fractureRegion: Joi.string().optional(),
  amputation: Joi.boolean().optional(),
  neckSwelling: Joi.boolean().optional(),
  minorHeadInjury: Joi.boolean().optional(),
  abrasion: Joi.boolean().optional(),
  suspectedAbuse: Joi.boolean().optional(),
  chestInjuryType: Joi.string().optional(),
  stabInjurySeverity: Joi.string().optional(),
  stabInjuryLocation: Joi.string().optional(),
  stabHeadScalp: Joi.boolean().optional(),
  stabHeadFace: Joi.boolean().optional(),
  stabHeadNeck: Joi.boolean().optional(),
  stabChestHeart: Joi.boolean().optional(),
  stabChestLungs: Joi.boolean().optional(),
  stabChestMajorBloodVessels: Joi.boolean().optional(),
  stabAbdomenStomach: Joi.boolean().optional(),
  stabAbdomenLiver: Joi.boolean().optional(),
  stabAbdomenKidneys: Joi.boolean().optional(),
  stabAbdomenSpleen: Joi.boolean().optional(),
  stabAbdomenIntestines: Joi.boolean().optional(),
  stabExtremityArm: Joi.boolean().optional(),
  stabExtremityLeg: Joi.boolean().optional(),
  stabExtremityMuscles: Joi.boolean().optional(),
  stabExtremityTendons: Joi.boolean().optional(),
  stabExtremityNerves: Joi.boolean().optional(),
  stabExtremityBloodVessels: Joi.boolean().optional(),
  pregnancy: Joi.boolean().optional(),
  pregnancyIssue: Joi.string().optional(),
  trimester: Joi.string().optional(),
  breathlessness: Joi.boolean().optional(),
  edema: Joi.boolean().optional(),
  internalBleeding: Joi.boolean().optional(),
  internalBleedingCause: Joi.string().optional(),
  poisoning: Joi.boolean().optional(),
  poisoningCause: Joi.string().optional(),
  burn: Joi.boolean().optional(),
  burnPercentage: Joi.string().optional(),
  hanging: Joi.boolean().optional(),
  drowning: Joi.boolean().optional(),
  electrocution: Joi.boolean().optional(),
  heatStroke: Joi.boolean().optional(),
  fever: Joi.boolean().optional(),
  feverSymptoms: Joi.string().optional(),
  drugOverdose: Joi.boolean().optional(),
  stoolPass: Joi.boolean().optional(),
  urinePass: Joi.boolean().optional(),
  swellingWound: Joi.boolean().optional(),
  dizziness: Joi.boolean().optional(),
  headache: Joi.boolean().optional(),
  coughCold: Joi.boolean().optional(),
  skinRash: Joi.boolean().optional(),
  medicoLegalExamination: Joi.boolean().optional()
});

module.exports = { triageSchema, triageFormSchema };
